ident = letter {letter | digit}.
integer = digit {digit}.
factor = ident | integer.
expression = factor {("+"|"-") factor}.
assignment = ident ":=" expression.
statement = [assignment].
StatementSequence = statement {";" statement}.
IdentList = ident {"," ident}.
ProcedureDeclaration = "PROCEDURE" ident ";"
    ["VAR" {IdentList ";"}]
    ["BEGIN" StatementSequence]
    "END" ident.
module = "MODULE" ident ";"
    {ProcedureDeclaration ";"}
    "END" ident "." .
